"""
Simple script for syncing the list of MHP specialities
"""

from ..models import Speciality

LIST_OF_SPECIALITIES = (
    (1, "DERM", "Dermatologist"),
    (2, "NEUR", "Neurologist"),
    (3, "CARD", "Cardiologist"),
    (4, "ORTH", "Orthopedic Surgeon"),
    (5, "PEDI", "Pediatrician"),
    (6, "PSYC", "Psychiatrist"),
    (7, "OBGY", "Obstetrician-Gynecologist"),
    (8, "ENT", "Otolaryngologist"),
    (9, "OPHTH", "Ophthalmologist"),
    (10, "ONC", "Oncologist"),
    (11, "ENDO", "Endocrinologist"),
    (12, "UROL", "Urologist"),
    (13, "GAST", "Gastroenterologist"),
    (14, "PLAS", "Plastic Surgeon"),
    (15, "RHEUM", "Rheumatologist"),
    (16, "ALLR", "Allergist/Immunologist"),
    (17, "PULM", "Pulmonologist"),
    (18, "NURSE", "Nurse Practitioner"),
    (19, "PHAR", "Pharmacist"),
    (20, "DIET", "Dietitian"),
    (21, "EMED", "Emergency Medicine Physician"),
    (22, "RADI", "Radiologist"),
    (23, "NURO", "Nurse Anesthetist"),
    (24, "PATH", "Pathologist"),
    (25, "OCCP", "Occupational Therapist"),
    (26, "PHYS", "Physical Therapist"),
    (27, "RESP", "Respiratory Therapist"),
    (28, "SOCW", "Social Worker"),
    (29, "PHED", "Physical Education Instructor"),
    (30, "CHIR", "Chiropractor"),
    (31, "RADT", "Radiation Therapist"),
    (32, "ORTT", "Orthotist"),
    (33, "OPTO", "Optometrist"),
    (34, "DENT", "Dentist"),
    (35, "PODI", "Podiatrist"),
    (36, "PHARMT", "Pharmacy Technician"),
    (37, "PERF", "Perfusionist"),
    (38, "NEPH", "Nephrologist"),
    (39, "VASC", "Vascular Surgeon"),
    (40, "NEURS", "Neurosurgeon"),
    (41, "AEMB", "Ambulance Emergency Assistant"),
    (42, "ANAES", "Anaesthetist's Assistant"),
    (43, "ARTS", "Arts Therapist"),
    (44, "ARTSI", "Arts Therapist Interns"),
    (45, "ARTSS", "Arts Therapy Student"),
    (46, "ASSCT", "Assistant Clinical Technologist"),
    (47, "ASMP", "Assistant Medical Orthotist Prosthetist & Leatherworker"),
    (48, "AUD", "Audiologist"),
    (49, "AUDM", "Audiometrician"),
    (50, "BAMB", "Basic Ambulance Assistant"),
    (51, "BIOK", "Biokineticist"),
    (52, "BME", "Biomedical Engineer"),
    (53, "CLINAS", "Clinical Associate"),
    (54, "CLBIO", "Clinical Biochemist"),
    (55, "CLTECH", "Clinical Technologist"),
    (56, "COMMSH", "Community Speech and Hearing Worker"),
    (57, "DENTAS", "Dental Assistant"),
    (58, "DENTASR", "Dental Assistant (Supplementary Register) - Closed"),
    (59, "DENTT", "Dental Therapist"),
    (60, "DENTST", "Dentist"),
    (61, "DIETVS", "Dietetics Visiting Student"),
    (62, "DIET", "Dietitian"),
    (63, "DISP", "Dispensing Optician"),
    (64, "ECPVS", "ECP Visiting Student"),
    (65, "ECTVS", "ECT Visiting Student"),
    (66, "EET", "Electro-Encephalographic Technician"),
    (67, "ECA", "Emergency Care Assistant"),
    (68, "ECP", "Emergency Care Practitioner"),
    (69, "ECT", "Emergency Care Technician"),
    (70, "EHA", "Environmental Health Assistant"),
    (71, "EHP", "Environmental Health Practitioner"),
    (72, "FOODI", "Food Inspector"),
    (73, "GENC", "Genetic Counsellor"),
    (74, "GRCT", "Graduate Clinical Technologist"),
    (75, "GRCTS", "Graduate Clinical Technologist Student"),
    (76, "HEA", "Health Assistant"),
    (77, "HAA", "Hearing Aid Acoustician"),
    (78, "INTERN", "Intern"),
    (79, "INTBIOK", "Intern Biokineticist"),
    (80, "INTBME", "Intern Biomedical Engineer"),
    (81, "INTCBIO", "Intern Clinical Biochemist"),
    (82, "INTGC", "Intern Genetic Counsellor"),
    (83, "INTMOP", "Intern Medical Orthotist and Prosthetist"),
    (84, "INTMP", "Intern Medical Physicist"),
    (85, "INTMS", "Intern Medical Scientist"),
    (86, "INTPSYC", "Intern Psychologist"),
    (87, "LABAS", "Laboratory Assistant"),
    (88, "MAS", "Masseur"),
    (89, "MBIO", "Medical Biological Scientist"),
    (90, "MLSCI", "Medical Laboratory Scientist"),
    (91, "MOP", "Medical Orthotist and Prosthetist"),
    (92, "MP", "Medical Physicist"),
    (93, "MPRA", "Medical Practitioner"),
    (94, "MSTU", "Medical Student"),
    (95, "MTECH", "Medical Technician"),
    (96, "MT", "Medical Technologist"),
    (97, "MTI", "Medical Technology Intern"),
    (98, "NUTVS", "Nutrition Visiting Student"),
    (99, "NUT", "Nutritionist"),
    (100, "OT", "Occupational Therapist"),
    (101, "OTA", "Occupational Therapy Assistant"),
    (102, "OTT", "Occupational Therapy Technician"),
    (103, "OECO", "Operational Emergency Care Orderly"),
    (104, "OPT", "Optometrist"),
    (105, "ORALH", "Oral Hygienist"),
    (106, "OFT", "Orthopaedic Footwear Technician"),
    (107, "OTAS", "Orthopaedic Technical Assistant"),
    (108, "ORTHO", "Orthoptist"),
    (109, "PARAM", "Paramedic"),
    (110, "PHYSIO", "Physiotherapist"),
    (111, "PTA", "Physiotherapy Assistant"),
    (112, "PTT", "Physiotherapy Technician"),
    (113, "POD", "Podiatrist"),
    (114, "PSYCHO", "Psycho-Technician"),
    (115, "PSYCHOL", "Psychologist"),
    (116, "PSVS", "Psychology Visiting Student"),
    (117, "PSYM", "Psychometrist"),
    (118, "RADTECH", "Radiation Technologist"),
    (119, "RADIOG", "Radiographer"),
    (120, "REGC", "Registered Counsellor"),
    (121, "REM", "Remedial Gymnast"),
    (122, "RESDR", "Restricted Supplementary Diagnostic Radiographer"),
    (123, "SAAD", "Speech and Audiology Assistant"),
    (124, "SHA", "Speech and Hearing Assistant"),
    (125, "SHC", "Speech and Hearing Correctionist"),
    (126, "ST", "Speech Therapist"),
    (127, "STA", "Speech Therapist and Audiologist"),
    (128, "STAASS", "Speech Therapy Assistant"),
    (129, "SVA", "STA Visiting Student"),
    (130, "STUDAMB", "Student Ambulance Emergency Assistant"),
    (131, "STUDANAES", "Student Anaesthetist's Assistant"),
    (132, "STUDASS", "Student Assistant Medical Orthotist Prosthetist & Leatherworker"),
    (133, "STUDAUD", "Student Audiologist"),
    (134, "STUDAUDM", "Student Audiometrician"),
    (135, "STUDBIOK", "Student Biokineticist"),
    (136, "STUDBME", "Student Biomedical Engineer"),
    (137, "STUDCLINAS", "Student Clinical Associate"),
    (138, "STUDCLBIO", "Student Clinical Biochemist"),
    (139, "STUDCLTECH", "Student Clinical Technologist"),
    (140, "STUDCOMMSH", "Student Community Speech and Hearing Worker"),
    (141, "STUDDENTAS", "Student Dental Assistant"),
    (142, "STUDDENTT", "Student Dental Therapist"),
    (143, "STUDDIET", "Student Dietitian"),
    (144, "STUDDISP", "Student Dispensing Optician"),
    (145, "STUDECP", "Student Emergency Care Practitioner"),
    (146, "STUDEN", "Student Environmental Health Assistant"),
    (147, "STUDEHP", "Student Environmental Health Practitioner"),
    (148, "STUDFOODI", "Student Food Inspector"),
    (149, "STUDGENC", "Student Genetic Counsellor"),
    (150, "STUDHAA", "Student Hearing Aid Acoustician"),
    (151, "STUDLABAS", "Student Laboratory Assistant"),
    (152, "STUDMAS", "Student Masseur"),
    (153, "STUDMBIO", "Student Medical Biological Scientist"),
    (154, "STUDMLSCI", "Student Medical Laboratory Scientist"),
    (155, "STUDMOP", "Student Medical Orthotist and Prosthetist"),
    (156, "STUDMP", "Student Medical Physicist"),
    (157, "STUDMPRA", "Student Medical Practitioner"),
    (158, "STUDMTECH", "Student Medical Technician"),
    (159, "STUDMT", "Student Medical Technologist"),
    (160, "STUDNUT", "Student Nutritionist"),
    (161, "STUDOT", "Student Occupational Therapist"),
    (162, "STUDOECO", "Student Operational Emergency Care Orderly"),
    (163, "STUDOPT", "Student Optometrist"),
    (164, "STUDORALH", "Student Oral Hygienist"),
    (165, "STUDOFT", "Student Orthopaedic Footwear Technician"),
    (166, "STUDOTAS", "Student Orthopaedic Technical Assistant"),
    (167, "STUDORTHO", "Student Orthoptist"),
    (168, "STUDPARAM", "Student Paramedic"),
    (169, "STUDPHYSIO", "Student Physiotherapist"),
    (170, "STUDPSYCHO", "Student Psycho-Technician"),
    (171, "STUDPSYCHOL", "Student Psychologist"),
    (172, "STUDPSYM", "Student Psychometrist"),
    (173, "STUDRADIOG", "Student Radiographer"),
    (174, "STUDREM", "Student Remedial Gymnast"),
    (175, "STUDSAAD", "Student Speech and Audiology Assistant"),
    (176, "STUDSHA", "Student Speech and Hearing Assistant"),
    (177, "STUDSHC", "Student Speech and Hearing Correctionist"),
    (178, "STUDST", "Student Speech Therapist"),
    (179, "STUDSTA", "Student Speech Therapist and Audiologist"),
    (180, "SUPAAS", "Supplementary Arts Assistant"),
    (181, "SUPAMB", "Supplementary Ambulance Emergency Assistant"),
    (182, "SUPARTS", "Supplementary Arts Therapist"),
    (183, "SUPBME", "Supplementary Biomedical Engineer"),
    (184, "SUPCLTECH", "Supplementary Clinical Technologist"),
    (185, "SUPCOMMSH", "Supplementary Community Speech and Hearing Worker"),
    (186, "SUPDENTT", "Supplementary Dental Therapist"),
    (187, "SUPDIET", "Supplementary Dietitian"),
    (188, "SUPDISP", "Supplementary Dispensing Optician"),
    (189, "SUPEHP", "Supplementary Environmental Health Practitioner"),
    (190, "SUPMOP", "Supplementary Medical Orthotist and Prosthetist"),
    (191, "SUPMT", "Supplementary Medical Technologist"),
    (192, "SUPNUT", "Supplementary Nutritionist"),
    (193, "SUPOT", "Supplementary Occupational Therapist"),
    (194, "SUPOPT", "Supplementary Optometrist"),
    (195, "SUPORALH", "Supplementary Oral Hygienist"),
    (196, "SUPORTHO", "Supplementary Orthoptist"),
    (197, "SUPPSYCHOL", "Supplementary Psychologist"),
    (198, "SUPREM", "Supplementary Remedial Gymnast"),
    (199, "SUPSTA", "Supplementary Speech Therapist and Audiologist"),
    (200, "SUPSTUD", "Supplementary Student"),
    (201, "SUPVS", "Supplementary Visiting Student"),
    (202, "VSTD", "Visiting Student"),
)


def run():
    for speciality in LIST_OF_SPECIALITIES:
        Speciality.objects.get_or_create(id=speciality[0], defaults={"symbol": speciality[1], "name": speciality[2]})
