# Generated by Django 4.2.6 on 2024-01-31 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0008_remove_practicelocation_doctors_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("datetime_booked", models.DateTimeField(auto_now_add=True)),
                ("datetime", models.DateTimeField()),
                ("reason", models.CharField(max_length=500)),
                (
                    "payment_process",
                    models.CharField(choices=[("BV", "Before Visit"), ("AV", "After Visit")], max_length=2),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "day",
                    models.CharField(
                        choices=[("MON", 1), ("TUE", 2), ("WED", 3), ("THU", 4), ("FRI", 5), ("SAT", 6), ("SUN", 7)],
                        max_length=3,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("doctor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="users.doctor")),
            ],
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "value",
                    models.PositiveSmallIntegerField(choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]),
                ),
                (
                    "appointment",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="appointments.appointment"),
                ),
                (
                    "giver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="giver", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receiver",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AppointmentType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("duration", models.SmallIntegerField()),
                ("is_online", models.BooleanField()),
                ("cost", models.DecimalField(decimal_places=2, max_digits=7)),
                ("no_show_cost", models.DecimalField(decimal_places=2, max_digits=7)),
                ("is_run_forever", models.BooleanField(default=True)),
                ("start_date", models.DateField(null=True)),
                ("end_date", models.DateField(null=True)),
                ("doctor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="users.doctor")),
            ],
        ),
        migrations.AddField(
            model_name="appointment",
            name="appointment_type",
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to="appointments.appointmenttype"),
        ),
        migrations.AddField(
            model_name="appointment",
            name="doctor",
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to="users.doctor"),
        ),
        migrations.AddField(
            model_name="appointment",
            name="patient",
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
