# Generated by Django 5.0.7 on 2024-08-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("datetime_booked", models.DateTimeField(auto_now_add=True)),
                ("start_time", models.DateTimeField()),
                ("reason", models.CharField(max_length=500)),
                (
                    "payment_process",
                    models.CharField(choices=[("BV", "Before Visit"), ("AV", "After Visit")], max_length=2),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AppointmentType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("duration", models.SmallIntegerField()),
                ("is_online", models.BooleanField()),
                ("cost", models.DecimalField(decimal_places=2, max_digits=7)),
                ("no_show_cost", models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True)),
                ("is_run_forever", models.BooleanField(default=True)),
                ("start_date", models.DateField(null=True)),
                ("end_date", models.DateField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "value",
                    models.PositiveSmallIntegerField(choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "day",
                    models.SmallIntegerField(
                        choices=[(1, "MON"), (2, "TUE"), (3, "WED"), (4, "THU"), (5, "FRI"), (6, "SAT"), (7, "SUN")]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
            ],
        ),
    ]
