# Generated by Django 4.2.6 on 2024-02-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0002_alter_appointment_doctor_alter_appointment_patient"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="timeslot",
            constraint=models.UniqueConstraint(
                models.F("doctor"),
                models.F("day"),
                models.F("start_time"),
                models.F("end_time"),
                name="unique_timeslot_configuration",
            ),
        ),
    ]
