# Generated by Django 5.0.7 on 2025-02-12 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="timeslot",
            options={"ordering": ["day", "start_time"]},
        ),
    ]
