# Generated by Django 4.2.6 on 2024-02-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0003_timeslot_unique_timeslot_configuration"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="timeslot",
            name="unique_timeslot_configuration",
        ),
        migrations.AddConstraint(
            model_name="timeslot",
            constraint=models.UniqueConstraint(
                fields=("doctor", "day", "start_time", "end_time"), name="unique_timeslot_configuration"
            ),
        ),
        migrations.AddConstraint(
            model_name="timeslot",
            constraint=models.UniqueConstraint(
                fields=("doctor", "day", "start_time"), name="same_start_time_timeslot"
            ),
        ),
        migrations.AddConstraint(
            model_name="timeslot",
            constraint=models.UniqueConstraint(fields=("doctor", "day", "end_time"), name="same_ebd_time_timeslot"),
        ),
    ]
