# Generated by Django 4.2.6 on 2024-03-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0005_appointment_date_created_appointment_date_modified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeslot",
            name="day",
            field=models.CharField(
                choices=[(1, "MON"), (2, "TUE"), (3, "WED"), (4, "THU"), (5, "FRI"), (6, "SAT"), (7, "SUN")],
                max_length=3,
            ),
        ),
    ]
