# Generated by Django 4.2.6 on 2024-03-05 14:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0007_alter_timeslot_day"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="datetime",
            new_name="start_time",
        ),
    ]
