# Generated by Django 4.2.6 on 2024-03-05 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0008_rename_datetime_appointment_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="appointment_type",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="appointments.appointmenttype"),
        ),
    ]
