# Generated by Django 5.0.3 on 2024-05-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0010_alter_appointmenttype_no_show_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmenttype",
            name="no_show_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True),
        ),
    ]
