# Generated by Django 5.0.7 on 2024-08-02 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0011_alter_appointmenttype_no_show_cost"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="payment",
            field=models.OneToOneField(
                default=None, on_delete=django.db.models.deletion.PROTECT, to="payments.payment"
            ),
            preserve_default=False,
        ),
    ]
