// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfeCpK99McKfVY56TXukDed1FWh7lt-Js',
    appId: '1:710242232170:android:be3df334ab3d95d3906713',
    messagingSenderId: '710242232170',
    projectId: 'pharmanathi-b3482',
    storageBucket: 'pharmanathi-b3482.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLmoD7QM-XguAdd0bdJ1-gyfDgATNjpfg',
    appId: '1:710242232170:ios:db657a82f8108c77906713',
    messagingSenderId: '710242232170',
    projectId: 'pharmanathi-b3482',
    storageBucket: 'pharmanathi-b3482.appspot.com',
    androidClientId: '710242232170-5b7ag0nh8sd216930nt2pvgktl3vo8jk.apps.googleusercontent.com',
    iosClientId: '710242232170-jetc349ucliase4l5t8v2lgebd6sphbu.apps.googleusercontent.com',
    iosBundleId: 'com.pharmanathi.patient',
  );

}