# Generated by Django 5.0.7 on 2024-08-27 14:07

import pharmanathi_backend.payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "_provider",
                    models.CharField(
                        blank=True,
                        choices=pharmanathi_backend.payments.models.Payment.get_provider_choices,
                        max_length=25,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("PAID", "Paid"), ("FAILED", "Failed")],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("json", models.JSONField(blank=True, null=True)),
                ("reverse_lookup_field", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
