# Generated by Django 5.0.7 on 2024-08-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[("PENDING", "Pending"), ("PAID", "Paid"), ("FAILED", "Failed")],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
