# Generated by Django 5.0.7 on 2024-08-02 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="json",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
