# Generated by Django 5.0.7 on 2024-08-14 13:06

import pharmanathi_backend.payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_payment_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="reverse_lookup_field",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="_provider",
            field=models.CharField(
                blank=True, choices=pharmanathi_backend.payments.models.Payment.get_provider_choices, max_length=25
            ),
        ),
    ]
