# Generated by Django 5.0.7 on 2024-08-14 13:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_payment_reverse_lookup_field_alter_payment__provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
