
volumes:
  pharmanathi_backend_local_postgres_data: {}
  pharmanathi_backend_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: ../
      dockerfile: ./pharmanathi.com/compose/local/django/Dockerfile
    image: pharmanathi_backend_local_django
    container_name: pharmanathi_backend_local_django
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - ..:/src:z
      - ./coverage_html:/coverage_html
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
      - ./.envs/.local/.verifi
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: pharmanathi_backend_production_postgres
    container_name: pharmanathi_backend_local_postgres
    volumes:
      - pharmanathi_backend_local_postgres_data:/var/lib/postgresql/data
      - pharmanathi_backend_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - 5433:5432

  docs:
    image: pharmanathi_backend_local_docs
    container_name: pharmanathi_backend_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./pharmanathi_backend:/app/pharmanathi_backend:z
    ports:
      - '9000:9000'
    command: /start-docs

  mailpit:
    image: axllent/mailpit:v1.8
    container_name: pharmanathi_backend_local_mailpit
    ports:
      - "8025:8025"

  redis:
    image: redis:6
    container_name: pharmanathi_backend_local_redis

  celeryworker:
    <<: *django
    image: pharmanathi_backend_local_celeryworker
    container_name: pharmanathi_backend_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailpit
      - verifi
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: pharmanathi_backend_local_celerybeat
    container_name: pharmanathi_backend_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailpit
      - verifi
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: pharmanathi_backend_local_flower
    container_name: pharmanathi_backend_local_flower
    ports:
      - '5555:5555'
    command: /start-flower

  web-driver:
    image: selenium/standalone-chrome:4.20.0-20240425
    restart: unless-stopped
    shm_size: 2gb
    ports:
      - 7900:7900

  verifi:
    depends_on:
      - web-driver
    build: ./verifi-standalone
    env_file: ./.envs/.local/.verifi
    volumes:
      - ./verifi-standalone/src:/app:z
    restart: unless-stopped
    ports:
      - 7901:8000

  verifi-sudo:
    image: python:3.11.9-slim-bullseye
    depends_on:
      - verifi
    ports:
      - 7902:8000
    volumes:
      - ./verifi-standalone/sudos:/www
    command: ['python', '-m', 'http.server', '8000', '-d', '/www']
