#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

IP=$(curl -s ifconfig.me)

# Prepare environment
source ./prepare-environment

if [[ $* == *--update* ]]; then
    printf "\n\n-------------- Getting System's latest version --------------\n"
    git checkout main
    git pull
fi


printf "\n\n--------------- Started updating DNS settings ---------------\n"
wget -O cloudflary.py https://raw.githubusercontent.com/Olfredos6/cloudflary.py/cli/cloudflary.py
# api.pharmanthi.com
python3 cloudflary.py update --record-id d6c008f070c1dcc4cdc31e55c1e7f346 --payload "{\"content\": \"$IP\"}"
# cdn.pharmanthi.com
python3 cloudflary.py update --record-id fd66e056a5ea3a7500ee41ac5e0c6e01 --payload "{\"content\": \"$IP\"}"
# pharmanathi.com
python3 cloudflary.py update --record-id 04ddd7337b39d54f602ca52dcb9637b7 --payload "{\"content\": \"$IP\"}"
rm cloudflary.py


# Rebuild images using the --build/--no-cache/--clean flags
DOCKER_BUILD_NO_CACHE=""
if [[ $* == *--no-cache* ]]; then
    DOCKER_BUILD_NO_CACHE="--no-cache"
fi

if [[ $* == *--build* ]]; then
    printf "\n\n--------------- Cleaning and building images --------------\n"
    if [[ $* == *--clean* ]]; then
        printf "Applying --clean option, removing existing images\n"
        docker image prune --all --force
    fi
    docker compose -f production.yml build $DOCKER_BUILD_NO_CACHE
fi

printf "\n\n----------------------- Running Django Migrations --------------------\n"
docker compose -f production.yml run --rm django python manage.py migrate

printf "\n\n------------------------ Syncing Social Apps... ----------------------\n"
docker compose -f production.yml run --rm django python manage.py runscript sync_social_apps

printf "\n\n------------------------ Syncing Specialities... ----------------------\n"
docker compose -f production.yml run --rm django python manage.py runscript sync_specialities

printf "\n\n-------------------------- Notifying via Discord ---------------------\n"
curl -X POST -H "Content-Type: application/json" \
    -d '{
            "username": "Pharmanathi Production Server Bot",
            "avatar_url": "https://avatars.githubusercontent.com/u/93515101?s=400&u=e55ddea588763060b73a80603344f13045535310&v=4",
            "embeds": [
                {
                    "title": "Production Server Status",
                    "description": "The production server is being started. Please verify comportment. You may access system health here.",
                    "color": 5763719,
                    "url": "https://www.pharmanthi.com"
                }
              ]
        }' $DISCORD_WEBHOOK_URL
printf Done

printf "\n\n------------------------ Starting Docker services -------------------\n"
exec docker compose -f production.yml up
