cb = {
    "data": {
        "id": 2009945086,
        "log": {
            "input": [],
            "errors": 0,
            "mobile": False,
            "history": [
                {"time": 3, "type": "action", "message": "Attempted to pay with card"},
                {"time": 4, "type": "success", "message": "Successfully paid with card"},
            ],
            "success": True,
            "attempts": 1,
            "start_time": 1660054888,
            "time_spent": 4,
        },
        "fees": 100,
        "plan": None,
        "split": {},
        "amount": 20000,
        "domain": "test",
        "paidAt": "2022-08-09T14:21:32.000Z",
        "source": None,
        "status": "success",
        "channel": "card",
        "message": None,
        "paid_at": "2022-08-09T14:21:32.000Z",
        "currency": "NGN",
        "customer": {
            "id": 89929267,
            "email": "hello@email.com",
            "phone": None,
            "metadata": None,
            "last_name": None,
            "first_name": None,
            "risk_action": "default",
            "customer_code": "CUS_i5yosncbl8h2kvc",
            "international_format_phone": None,
        },
        "metadata": "",
        "order_id": None,
        "createdAt": "2022-08-09T14:20:57.000Z",
        "reference": "q3x2r8p8o1",
        "created_at": "2022-08-09T14:20:57.000Z",
        "fees_split": None,
        "ip_address": "100.64.11.35",
        "subaccount": {},
        "plan_object": {},
        "authorization": {
            "bin": "408408",
            "bank": "TEST BANK",
            "brand": "visa",
            "last4": "4081",
            "channel": "card",
            "exp_year": "2030",
            "reusable": True,
            "card_type": "visa ",
            "exp_month": "12",
            "signature": "SIG_yEXu7dLBeqG0kU7g95Ke",
            "account_name": None,
            "country_code": "NG",
            "authorization_code": "AUTH_ahisucjkru",
        },
        "fees_breakdown": None,
        "gateway_response": "Successful",
        "requested_amount": 20000,
        "transaction_date": "2022-08-09T14:20:57.000Z",
        "pos_transaction_data": None,
    },
    "status": True,
    "message": "Verification successful",
}
