name: pharma_nathi
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  cupertino_icons: ^1.0.2
  fl_chart: ^0.69.0
  google_sign_in: ^6.2.0
  provider: ^6.1.1
  path_provider: ^2.1.3
  shared_preferences: ^2.3.2
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  flutter_secure_storage: ^9.0.0
  http: ^1.2.2
  device_info: ^2.0.3
  location: ^7.0.0

  icons_launcher: ^3.0.0
  logger: ^2.4.0
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0
  multi_select_flutter: ^4.1.3
  flutter_svg: ^2.0.10+1
  sentry_flutter: 8.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.3.0
  patrol: ^3.13.1
  integration_test:
    sdk: flutter

patrol:
  app_name: Pharmanthi Medical Professional
  android:
    package_name: com.pharmanathi.mhp
  ios:
    bundle_id: com.pharmanathi.mobileMhp


flutter:
  assets:
    - assets/sample.json
    - assets/images/
    - .env.development
    - .env.production
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-VariableFont_wdth,wght.ttf  
  uses-material-design: true

icons_launcher:
  image_path: "assets/images/pharmanathi-mhp-icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
