name: client_pharmanathi
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
   sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  table_calendar: ^3.0.9
  file_picker: ^8.0.7
  google_sign_in: ^6.2.0
  path_provider: ^2.1.4
  provider: ^6.0.0
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  shared_preferences: ^2.3.2
  location: ^5.0.3
  device_info: ^2.0.3
  flutter_secure_storage: ^9.0.0
  flutter_dotenv: ^5.1.0
  http: ^1.2.2
  icons_launcher: ^2.1.7
  logger: ^2.4.0
  sentry_flutter: ^8.8.0
  webview_flutter: ^3.0.4
  flutter_bloc: ^8.0.0
  # url_launcher: ^6.3.0
  uni_links: ^0.5.1 # @TODO(nehemie): move to app_links(https://pub.dev/packages/app_links)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  change_app_package_name: ^1.3.0

flutter:
  assets:
    - assets/sample.json
    - assets/images/
    - .env
  uses-material-design: true

icons_launcher:
  image_path: "assets/images/pharmanathi-patient-icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
