name: client_pharmanathi
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
   sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  table_calendar: ^3.0.9
  file_picker: ^6.1.1
  google_sign_in: ^6.2.0
  path_provider: ^2.0.13
  provider: ^5.0.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  shared_preferences: ^2.0.9
  location: ^5.0.3
  device_info: ^2.0.3
  flutter_secure_storage: ^9.0.0
  flutter_dotenv: ^5.1.0
  http: ^1.2.0
  icons_launcher: ^2.1.7
  logger: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  change_app_package_name: ^1.1.0

flutter:
  assets:
    - assets/sample.json
    - assets/images/
    - .env
  uses-material-design: true

icons_launcher:
  image_path: "assets/images/pharmanathi-patient-icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
