# Generated by Django 4.2.6 on 2024-01-16 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("line_1", models.CharField(max_length=100)),
                ("line_2", models.CharField(max_length=100)),
                ("suburb", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("province", models.CharField(max_length=50)),
                ("lat", models.DecimalField(decimal_places=3, max_digits=13)),
                ("long", models.DecimalField(decimal_places=3, max_digits=13)),
            ],
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_verified", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Speciality",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="PracticeLocation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                ("address", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="users.address")),
                ("doctors", models.ManyToManyField(to="users.doctor")),
            ],
        ),
        migrations.AddField(
            model_name="doctor",
            name="speciality",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="users.speciality"),
        ),
        migrations.AddField(
            model_name="doctor",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
