# Generated by Django 5.0.7 on 2025-02-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="device_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
