# Generated by Django 4.2.6 on 2024-01-17 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_address_doctor_speciality_practicelocation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="speciality",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="users.speciality"),
        ),
    ]
