# Generated by Django 4.2.6 on 2024-01-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_address_date_created_address_date_modified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speciality",
            name="id",
            field=models.SmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
