# Generated by Django 4.2.6 on 2024-01-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_speciality_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="speciality",
            name="symbol",
            field=models.CharField(default="NULL", max_length=7),
            preserve_default=False,
        ),
    ]
