# Generated by Django 4.2.6 on 2024-01-17 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_speciality_symbol"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="speciality",
        ),
        migrations.AddField(
            model_name="doctor",
            name="specialities",
            field=models.ManyToManyField(to="users.speciality"),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="user",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
