# Generated by Django 4.2.6 on 2024-01-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_remove_doctor_speciality_doctor_specialities_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="practicelocation",
            name="doctors",
        ),
        migrations.AddField(
            model_name="doctor",
            name="practicelocations",
            field=models.ManyToManyField(to="users.practicelocation"),
        ),
    ]
