# Generated by Django 4.2.6 on 2024-01-31 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_remove_practicelocation_doctors_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="lat",
            field=models.DecimalField(decimal_places=10, max_digits=13),
        ),
        migrations.AlterField(
            model_name="address",
            name="long",
            field=models.DecimalField(decimal_places=10, max_digits=13),
        ),
    ]
