# Generated by Django 4.2.6 on 2024-01-31 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_address_lat_alter_address_long"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="line_2",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
