# Generated by Django 4.2.6 on 2024-02-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_alter_address_line_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="_profile_pic",
            field=models.URLField(blank=True, null=True),
        ),
    ]
