# Generated by Django 4.2.6 on 2024-02-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_user__profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, verbose_name="First name of User"),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, verbose_name="Last name of User"),
        ),
    ]
