# Generated by Django 4.2.6 on 2024-02-25 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_user_first_name_user_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="hpcsa_no",
            field=models.CharField(max_length=5, null=True, verbose_name="HPCSA No."),
        ),
        migrations.AddField(
            model_name="doctor",
            name="mp_no",
            field=models.CharField(max_length=5, null=True, verbose_name="Mp No."),
        ),
        migrations.AddField(
            model_name="user",
            name="contact_no",
            field=models.CharField(max_length=15, null=True, verbose_name="Contact Number"),
        ),
        migrations.AddField(
            model_name="user",
            name="initials",
            field=models.CharField(max_length=5, null=True, verbose_name="Initials"),
        ),
        migrations.AddField(
            model_name="user",
            name="sa_id_no",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MaxLengthValidator(limit_value=13, message="Must be exactly 13 digits."),
                    django.core.validators.MinLengthValidator(limit_value=13, message="Must be exactly 13 digits."),
                ],
                verbose_name="South African ID Number",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="title",
            field=models.CharField(
                choices=[("Mr", "Mr"), ("Miss", "Miss"), ("Mrs", "Mrs"), ("Ms", "Ms")],
                max_length=5,
                null=True,
                verbose_name="Title",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="university",
            field=models.CharField(max_length=100, null=True, verbose_name="University"),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, verbose_name="First name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, verbose_name="Last name"),
        ),
    ]
