# Generated by Django 4.2.6 on 2024-02-27 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_doctor_hpcsa_no_doctor_mp_no_user_contact_no_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="is_verified",
        ),
        migrations.AlterField(
            model_name="doctor",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="doctor_profile", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
