# Generated by Django 5.0.3 on 2024-06-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_alter_user_options_user_date_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="_is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
