# Generated by Django 5.0.6 on 2024-06-17 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_doctor__is_verified"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvalidationReason",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("text", models.TextField()),
                ("is_resolved", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("mhp", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="users.doctor")),
                (
                    "resolved_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resolver",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
