# Generated by Django 5.0.6 on 2024-06-17 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_invalidationreason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invalidationreason",
            name="resolved_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resolver",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
