# Generated by Django 5.0.6 on 2024-06-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_alter_invalidationreason_resolved_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="line_2",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="hpcsa_no",
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name="HPCSA No."),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="mp_no",
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name="Mp No."),
        ),
    ]
