# Generated by Django 5.0.6 on 2024-06-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_alter_address_line_2_alter_doctor_hpcsa_no_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="lat",
            field=models.DecimalField(decimal_places=13, max_digits=16),
        ),
        migrations.AlterField(
            model_name="address",
            name="long",
            field=models.DecimalField(decimal_places=13, max_digits=16),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="hpcsa_no",
            field=models.CharField(max_length=5, null=True, verbose_name="HPCSA No."),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="mp_no",
            field=models.CharField(max_length=5, null=True, verbose_name="Mp No."),
        ),
    ]
