# Generated by Django 5.0.6 on 2024-06-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_alter_address_lat_alter_address_long_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="hpcsa_no",
            field=models.CharField(default="Error", max_length=5, verbose_name="HPCSA No."),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="doctor",
            name="mp_no",
            field=models.CharField(default="Error", max_length=5, verbose_name="Mp No."),
            preserve_default=False,
        ),
    ]
