# Generated by Django 5.0.6 on 2024-06-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_alter_doctor_hpcsa_no_alter_doctor_mp_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speciality",
            name="symbol",
            field=models.CharField(max_length=20),
        ),
    ]
