# Generated by Django 5.0.6 on 2024-06-25 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_alter_speciality_symbol"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("report", models.JSONField()),
                ("type", models.CharField(max_length=7)),
                (
                    "mp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verification_reports",
                        to="users.doctor",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
