# Generated by Django 5.0.6 on 2024-06-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_verificationreport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="mp_no",
            field=models.CharField(max_length=20, verbose_name="Mp No."),
        ),
    ]
