# Generated by Django 5.0.6 on 2024-06-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_alter_doctor_mp_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationreport",
            name="type",
            field=models.CharField(choices=[("pharma", "pharma"), ("mp", "mp")], max_length=7),
        ),
    ]
