# Generated by Django 5.0.6 on 2024-06-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0027_alter_verificationreport_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationreport",
            name="type",
            field=models.CharField(choices=[("pharma", "pharma"), ("mp", "mp")], editable=False, max_length=7),
        ),
    ]
