# Generated by Django 5.0.6 on 2024-06-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0028_alter_verificationreport_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="hpcsa_no",
            field=models.CharField(max_length=12, verbose_name="HPCSA No."),
        ),
    ]
