# Generated by Django 5.0.6 on 2024-06-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0029_alter_doctor_hpcsa_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationreport",
            name="type",
            field=models.CharField(choices=[("pharma", "pharma"), ("hpcsa", "hpcsa")], editable=False, max_length=7),
        ),
    ]
