# Generated by Django 5.0.6 on 2024-06-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0030_alter_verificationreport_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationreport",
            name="type",
            field=models.CharField(choices=[("SAPC", "SAPC"), ("HPCSA", "HPCSA")], editable=False, max_length=7),
        ),
    ]
