# Generated by Django 5.0.7 on 2024-07-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0031_alter_verificationreport_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speciality",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
