# Generated by Django 5.0.7 on 2024-07-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0032_alter_speciality_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="lat",
            field=models.DecimalField(decimal_places=13, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="long",
            field=models.DecimalField(decimal_places=13, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="province",
            field=models.CharField(
                choices=[
                    ("EC", "Eastern Cape"),
                    ("FS", "Free State"),
                    ("GP", "Gauteng"),
                    ("KZN", "KwaZulu-Natal"),
                    ("LP", "Limpopo"),
                    ("NC", "Northern Cape"),
                    ("NW", "North-West"),
                    ("WC", "Western Cape"),
                ]
            ),
        ),
    ]
