# Generated by Django 5.0.7 on 2024-07-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0033_alter_address_lat_alter_address_long_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="province",
            field=models.CharField(
                choices=[
                    ("EC", "Eastern Cape"),
                    ("FS", "Free State"),
                    ("GP", "Gauteng"),
                    ("KZN", "KwaZulu-Natal"),
                    ("LP", "Limpopo"),
                    ("NC", "Northern Cape"),
                    ("NW", "North-West"),
                    ("WC", "Western Cape"),
                ],
                max_length=3,
            ),
        ),
    ]
