# Generated by Django 5.0.7 on 2024-08-16 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0034_alter_address_province"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="mp_no",
            field=models.CharField(max_length=20, null=True, verbose_name="Mp No."),
        ),
    ]
