#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py migrate

echo 'Syncing Social Apps'
python manage.py runscript sync_social_apps

echo 'Sync Specialities'
python manage.py runscript sync_specialities

exec uvicorn config.asgi:application --host 0.0.0.0 --reload --reload-include '*.html'
