name: Milestone Notifier

on:
  milestone:
    types: [created, opened, closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Set env variables
        run: |
          if [ "${{ github.event.action }}" = "created" ]; then
            echo "embed_color=3447003" >> "$GITHUB_ENV"
            echo "event_action=started" >> "$GITHUB_ENV"
          elif [ "${{ github.event.action }}" = "opened" ]; then
            echo "embed_color=15844367" >> "$GITHUB_ENV"
            echo "event_action=opened" >> "$GITHUB_ENV"
          elif [ "${{ github.event.action }}" == "closed" ]; then
            echo "embed_color=3066993" >> "$GITHUB_ENV"
            echo "event_action=closed" >> "$GITHUB_ENV"
          fi
      
      - name: Get description
        run: echo "milestone_description=$(jq -Rs . <<< '${{ github.event.milestone.description }}')" >> $GITHUB_ENV

      - name: Send notification to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          echo "Color is ${{ env.embed_color }}"
          echo "Action is  ${{ env.event_action }}"
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
                "username": "GitHub Actions",
                "embeds": [
                    {
                        "author": {
                            "name": "${{ github.event.sender.login }}",
                            "icon_url": "${{ github.event.sender.avatar_url }}",
                            "url": "${{ github.event.sender.url }}"
                        },
                        "title": "Sprint/Milestone ${{ github.event.milestone.title }}",
                        "description": "The sprint was **${{ env.event_action }}** by **${{ github.event.sender.login }}**.\n**:information_source:More info**:\\n*Due Date* ${{ github.event.milestone.due_on }}\n*",
                        "color": ${{ env.embed_color }},
                        "url": "${{ github.event.milestone.html_url }}"
                    },
                    {
                        "description": ${{ env.milestone_description }}
                    }
                  ]
              }' $DISCORD_WEBHOOK_URL
      
      - name: Print milestone information
        run: |
          echo "Milestone Title: ${{ github.event.milestone.title }}"
          echo "Milestone Description: ${{ github.event.milestone.description }}"
          echo "Milestone Due On: ${{ github.event.milestone.due_on }}"
          echo "Milestone State: ${{ github.event.milestone.state }}"
          echo "Milestone URL: ${{ github.event.milestone.html_url }}"
          echo " ${{ github.event.milestone }}"
          
      # - name: Send Notification
      #   uses: th0th/notify-discord@v0.4.1
      #   if: ${{ always() }}
      #   env:
      #     DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      #     GITHUB_ACTOR: ${{ github.actor }}
      #     GITHUB_JOB_NAME: "Build and deploy"
      #     GITHUB_JOB_STATUS: ${{ job.status }}
