name: Milesone Notifier

on:
  milestone:
    types: [opened, deleted]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification
        uses: th0th/notify-discord@v0.4.1
        if: ${{ always() }}
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_MILESTONE_WEBHOOK_URL }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_JOB_NAME: "Build and deploy"
          GITHUB_JOB_STATUS: ${{ job.status }}
