name: Milestone Notifier

on:
  milestone:
    types: [created, opened, closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          if [ "${{ github.event.action }}" == "created" || "${{ github.event.action }}" == "opened" ]; then
            COLOR=3066993  # Green for created
            ACTION="started"
          elif [ "${{ github.event.action }}" == "closed" ]; then
            COLOR=3447003  # Blue for closed
            ACTION="ended"
          fi

          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
                "username": "GitHub Actions",
                "embeds": [
                    {
                        "author": {
                            "name": "${{ github.event.sender.login }}",
                            "icon_url": "${{ github.event.sender.avatar_url }}",
                            "url": "${{ github.event.sender.url }}"
                        },
                        "title": "Sprint/Milestone ${{ github.event.milestone.title }}",
                        "description": "The spint or milestone was **${ACTION}** by **${{ github.event.sender.login }}**.\n:information_source: **More info**:\n*Due Date* ${{ github.event.milestone.due_on }}\n*Description*: ${{ github.event.milestone.description }}",
                        "color": "${COLOR}",
                        "url": "${{ github.event.milestone.html_url }}"
                    }
                  ]
              }' $DISCORD_WEBHOOK_URL
      
      - name: Print milestone information
        run: |
          echo "Milestone Title: ${{ github.event.milestone.title }}"
          echo "Milestone Description: ${{ github.event.milestone.description }}"
          echo "Milestone Due On: ${{ github.event.milestone.due_on }}"
          echo "Milestone State: ${{ github.event.milestone.state }}"
          echo "Milestone URL: ${{ github.event.milestone.html_url }}"
          echo " ${{ github.event.milestone }}"
          
      # - name: Send Notification
      #   uses: th0th/notify-discord@v0.4.1
      #   if: ${{ always() }}
      #   env:
      #     DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      #     GITHUB_ACTOR: ${{ github.actor }}
      #     GITHUB_JOB_NAME: "Build and deploy"
      #     GITHUB_JOB_STATUS: ${{ job.status }}
